import{a as v,S as $,i as a}from"./assets/vendor-CrlV4O_2.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&c(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const P="50781688-4c5e14a62117c7affe0b16869",E="https://pixabay.com/api/",B=15;async function f(r,t=1){try{return(await v.get(E,{params:{key:P,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:B}})).data}catch{throw new Error("Failed to fetch images")}}const m=document.querySelector(".gallery"),y=document.querySelector(".loader"),h=document.querySelector('button[type="button"]'),C=new $(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom"});function b(r){const t=r.map(({webformatURL:n,largeImageURL:c,tags:e,likes:o,views:s,comments:S,downloads:q})=>`
        <li class="gallery-item">
          <a href="${c}">
            <img src="${n}" alt="${e.split(" ").slice(0,3).join(" ").replace(/,+$/,"")}" class="gallery-img" loading="lazy" />
          </a>
          <div class="info">
            <p><b>Likes:</b> ${o}</p>
            <p><b>Views:</b> ${s}</p>
            <p><b>Comments:</b> ${S}</p>
            <p><b>Downloads:</b> ${q}</p>
          </div>
        </li>
      `).join("");m.insertAdjacentHTML("beforeend",t),C.refresh()}function M(){m.innerHTML=""}function L(){y.classList.add("is-visible")}function u(){y.classList.remove("is-visible")}function R(){h.style.display="block"}function d(){h.style.display="none"}const g=document.querySelector(".form"),O=g.querySelector('input[name="search-text"]'),x=document.querySelector('button[type="button"]');document.querySelector(".loader");const A=document.querySelector(".gallery");let l="",i=1;const w=15;let p=0;g.addEventListener("submit",H);x.addEventListener("click",I);async function H(r){if(r.preventDefault(),l=O.value.trim(),i=1,!l){a.warning({message:"Please enter a search query!",position:"topRight",backgroundColor:"#f1c40f"});return}M(),d(),L();try{const t=await f(l,i);if(u(),!t.hits.length){a.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"red"});return}p=t.totalHits,b(t.hits),p>i*w?R():d()}catch(t){u(),a.error({message:`Something went wrong: ${t.message}`,position:"topRight"})}finally{g.reset()}}async function I(){L(),i+=1;try{const r=await f(l,i);u(),b(r.hits);const{height:t}=A.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),i*w>=p&&(d(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"#3498db"}))}catch(r){u(),a.error({message:`Something went wrong: ${r.message}`,position:"topRight"})}}
//# sourceMappingURL=index.js.map
